--- #YAML:1.0
name:               SMS-CPAGateway
version:            0.01
abstract:           Send an SMS through a gateway using the CPA Gateway protocol
author:
    - Eskild Hustvedt <zerodogg@cpan.org>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Any::Moose:      0
    LWP::UserAgent:  0
    URI::Encode:     0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
